# This workflow will build a Java project with Maven
##
## More details on https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-java-with-maven

name: Code Quality Composite Action

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - java-app/**


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    defaults:
      run:
        # Set the working directory to the java-app directory
        # works only for the shell.
        working-directory: java-app
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - uses: ./.github/actions/composite
      name: composite action
      with:
       working-directory: java-app