name: greetings coder

on: [pull_request, issues]

jobs:
  welcome_coder:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
     - name: "greetings_message"
       run: echo 'Welcome code owner'
     - uses: actions/first-interaction@v1
       name: "first interaction github official action"
       with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Message that will be displayed on users' first issue"
          pr-message: "Message that will be displayed on users' first pull request"
       